6 get article comments
ELR143/elr143-news-server pull request #6
Opened 2023-11-21 15:48 UTC by ELR143

2023-11-21 16:08 UTC, popatre requested changes
Some good stuff - missing some tests though:

- [ ] Status 200: OK
Responds with empty array if article_id is valid but has no associated comments.
- [ ] Status 400: Bad request, invalid article_id
E.g. GET /api/articles/notanumber/comments

2023-11-22 11:01 UTC, nc-verity-gregory approved these changes
Nicely done. Merge away!

2023-11-22 11:01 UTC, ghost commented on models/news-model.js
> +    console.log(articleComments.rows);
👀

2023-11-22 11:01 UTC, ghost commented on models/utils-model.js
> +    }
Niiiiice

2023-11-22 11:21 UTC, merged